# theme       : jekyll-theme-slate
title       : "Flashcart Labels"
description : "A repository for flashcart labels"
repo        : "Sanrax/cart-labels"
color       : "#B23456"
image       : "/assets/images/favicon/favicon-196x196.png"

sass:
  sass_dir: _sass

exclude:
  - Gemfile*
  - vendor
  - LICENSE*

defaults:
  - scope:
      path: "**/*.md"
    values:
      layout: app

collections:
  labels:
    output: true
